services:
  haproxy:
    image: haproxy:3.2.25-trixie
    container_name: haproxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs:/certs
    networks:
      - proxy

networks:
  proxy:
    external: true